application: your-app-id
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /_assets
  static_dir: _assets

- url: /.*
  script: app.application
  
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
